### ISSUE TITLE
error while trying to run npm start

### ISSUE THREAD

**Issue by IncredibleMrTim** [risenforces/craco-alias#2]
Hi

After making the changes you suggested in [issue/1](https://github.com/risenforces/craco-alias/issues/1) i get the following errors...

```
internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.basename (path.js:1289:5)
    at checkConfig (/Users/ME/Documents/Projects/react/XXX/xxx-ui/node_modules/craco-alias/plugin/pre-check/check-config.js:9:31)
    at preCheck (/Users/ME/Documents/Projects/react/XXX/xxx-ui/node_modules/craco-alias/plugin/pre-check/index.js:18:5)
    at Object.cracoOptions [as overrideWebpackConfig] (/Users/ME/Documents/Projects/react/XXX/xxx-ui/node_modules/craco-alias/plugin/create-overrider.js:6:3)
    at overrideWebpack (/Users/ME/Documents/Projects/react/XXX/xxx-ui/node_modules/@craco/craco/lib/features/plugins.js:42:40)
    at cracoConfig.plugins.forEach.x (/Users/ME/Documents/Projects/react/XXX/xxx-ui/node_modules/@craco/craco/lib/features/plugins.js:64:29)
    at Array.forEach (<anonymous>)
    at applyWebpackConfigPlugins (/Users/ME/Documents/Projects/react/XXX/xxx-ui/node_modules/@craco/craco/lib/features/plugins.js:63:29)
    at mergeWebpackConfig (/Users/ME/Documents/Projects/react/XXX/xxx-ui/node_modules/@craco/craco/lib/features/webpack/merge-webpack-config.js:67:30)
    at overrideWebpackDev (/Users/ME/Documents/Projects/react/XXX/xxx-ui/node_modules/@craco/craco/lib/features/webpack/override.js:11:36)
    at Object.<anonymous> (/Users/ME/Documents/Projects/react/XXX/xxx-ui/node_modules/@craco/craco/scripts/start.js:19:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
```

**Comment by risenforces** [comment]
@IncredibleMrTim It looks like that there is no `appJsConfig` in CRA `paths` object. So, it's not `craco-alias` fault. What is your `react-scripts` version?

**Comment by IncredibleMrTim** [comment]
Hey @risenforces , this seems to work great, turn out that my react-scripts were way out of date, however, i still get an issue where my `src/index.js` file is being included in  my coverage test even though it is excluded?

```
	"jest": {
		"collectCoverageFrom": [
			"src/**/**/**/*.js",
			"src/**/**/**/*.jsx",
			"!src/setupTests.js",
			"!src/**/stories/*.js",
			"!src/index.js"
		]
	},
```

all other excluded files seem to be fine accept this one?
